//AUTH CONSTANTS

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const USER_MAIL_REQUEST = "USER_MAIL_REQUEST";
export const USER_MAIL_SUCCESS = "USER_MAIL_SUCCESS";
export const USER_MAIL_FAILURE = "USER_MAIL_FAILURE";

export const USER_RESET_REQUEST = "USER_RESET_REQUEST";
export const USER_RESET_SUCCESS = "USER_RESET_SUCCESS";
export const USER_RESET_FAILURE = "USER_RESET_FAILURE";

export const USER_CHANGE_PASS_REQUEST = "USER_CHANGE_PASS_REQUEST";
export const USER_CHANGE_PASS_SUCCESS = "USER_CHANGE_PASS_SUCCESS";
export const USER_CHANGE_PASS_FAILURE = "USER_CHANGE_PASS_FAILURE";

//ROLE BASED CONSTATNTS
export const USER_ADD_REQUEST = "USER_ADD_REQUEST";
export const USER_ADD_SUCCESS = "USER_ADD_SUCCESS";
export const USER_ADD_FAILURE = "USER_ADD_FAILURE";

export const USER_FETCH_ROLE_REQUEST = "USER_FETCH_ROLE_REQUEST";
export const USER_FETCH_ROLE_SUCCESS = "USER_FETCH_ROLE_SUCCESS";
export const USER_FETCH_ROLE_FAILURE = "USER_FETCH_ROLE_FAILURE";

export const USER_FETCH_ID_REQUEST = "USER_FETCH_ID_REQUEST";
export const USER_FETCH_ID_SUCCESS = "USER_FETCH_ID_SUCCESS";
export const USER_FETCH_ID_FAILURE = "USER_FETCH_ID_FAILURE";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAILURE = "USER_DELETE_FAILURE";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAILURE = "USER_UPDATE_FAILURE";

export const USER_APPROVAL_STATUS_REQUEST = "USER_APPROVAL_STATUS_REQUEST";
export const USER_APPROVAL_STATUS_SUCCESS = "USER_APPROVAL_STATUS_SUCCESS";
export const USER_APPROVAL_STATUS_FAILURE = "USER_APPROVAL_STATUS_FAILURE";

export const LOGIN_USER_FETCH_ID_REQUEST = "LOGIN_USER_FETCH_ID_REQUEST";
export const LOGIN_USER_FETCH_ID_SUCCESS = "LOGIN_USER_FETCH_ID_SUCCESS";
export const LOGIN_USER_FETCH_ID_FAILURE = "LOGIN_USER_FETCH_ID_FAILURE";

export const RESUME_ADD_REQUEST = "RESUME_ADD_REQUEST";
export const RESUME_ADD_SUCCESS = "RESUME_ADD_SUCCESS";
export const RESUME_ADD_FAILURE = "RESUME_ADD_FAILURE";

export const RESUME_GET_FAILURE = "RESUME_GET_FAILURE";
export const RESUME_GET_SUCCESS = "RESUME_GET_SUCCESS";
export const RESUME_GET_REQUEST = "RESUME_GET_REQUEST";

export const CATEGORY_ADD_REQUEST = "CATEGORY_ADD_REQUEST";
export const CATEGORY_ADD_SUCCESS = "CATEGORY_ADD_SUCCESS";
export const CATEGORY_ADD_FAILURE = "CATEGORY_ADD_FAILURE";

export const CATEGORY_IMAGE_ADD_REQUEST = "CATEGORY_IMAGE_ADD_REQUEST";
export const CATEGORY_IMAGE_ADD_SUCCESS = "CATEGORY_IMAGE_ADD_SUCCESS";
export const CATEGORY_IMAGE_ADD_FAILURE = "CATEGORY_IMAGE_ADD_FAILURE";

export const CATEGORY_GET_FAILURE = "CATEGORY_GET_FAILURE";
export const CATEGORY_GET_SUCCESS = "CATEGORY_GET_SUCCESS";
export const CATEGORY_GET_REQUEST = "CATEGORY_GET_REQUEST";

export const CATEGORY_IMAGE_GET_FAILURE = "CATEGORY_IMAGE_GET_FAILURE";
export const CATEGORY_IMAGE_GET_SUCCESS = "CATEGORY_IMAGE_GET_SUCCESS";
export const CATEGORY_IMAGE_GET_REQUEST = "CATEGORY_IMAGE_GET_REQUEST";

export const RESUME_DELETE_FAILURE = "RESUME_DELETE_FAILURE";
export const RESUME_DELETE_SUCCESS = "RESUME_DELETE_SUCCESS";
export const RESUME_DELETE_REQUEST = "RESUME_DELETE_REQUEST";

export const USER_FETCH_FAILURE = "USER_FETCH_FAILURE";
export const USER_FETCH_SUCCESS = "USER_FETCH_SUCCESS";
export const USER_FETCH_REQUEST = "USER_FETCH_REQUEST";
